name: Weekly Heavy Tests

on:
  schedule:
    - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
  heavy-tests:
    name: Full Suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        uses: |
          uv venv --allow-existing
          uv pip install openmim
          sed '/torch/d' docker/install/requirements.txt > requirements_ci.txt
          uv pip install -r requirements_ci.txt
          uv pip install torch==2.2.1 torchvision==0.17.1 --index-url https://download.pytorch.org/whl/cpu
          uv run mim install "mmcv==2.1.0"
          uv pip install --no-deps -e

      - name: Run All tests
        run: uv run pytest